print ("Welcome to this simple program")
name = input("What is your name? ")
print ("Hello " + name)
age = input("How old are you? ")
home = input("Where do you come from? ")
animal = input("What is your favourite animal? ")
print (name + " so you are " + age + " years old, you come from " + home + " and your favorite animal is " + animal)